services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: ./todo-backend/dev.Dockerfile
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
      - PORT=3000
    volumes:
      - ./todo-backend:/usr/src/app
    depends_on:
      - mongo
      - redis
